#!/bin/bash

runWiscJobs.py \
  --WorkFlow KennyMG_sig_30TeV \
  --Executable=runMG_Del.sh \
  --Arguments=mc-sig_30TeV.txt \
  --nJobs=1000 \
  --TransferInputFile=/nfs_scratch/hjia38/transferInputFiles.tar.gz,mc-sig_30TeV.txt\
  --OutputDir=/nfs_scratch/$USER \
  --HDFSProdDir None  \
  --Experiment mucol \
  --DiskRequirements 50000

runWiscJobs.py \
  --WorkFlow KennyMG_vvzh_30TeV \
  --Executable=runMG_Del.sh \
  --Arguments=mc-bkgvvzh_30TeV.txt \
  --nJobs=1000 \
  --TransferInputFile=/nfs_scratch/hjia38/transferInputFiles.tar.gz,mc-bkgvvzh_30TeV.txt\
  --OutputDir=/nfs_scratch/$USER \
  --OutputDir=/hdfs/store/user/hjia38 \
  --HDFSProdDir None \
  --Experiment mucol \
  --DiskRequirements 50000

runWiscJobs.py \
  --WorkFlow KennyMG_vvqqz_30TeV \
  --Executable=runMG_Del.sh \
  --Arguments=mc-bkgvvqqz_30TeV.txt \
  --nJobs=1000 \
  --TransferInputFile=/nfs_scratch/hjia38/transferInputFiles.tar.gz,mc-bkgvvqqz_30TeV.txt\
  --OutputDir=/nfs_scratch/$USER \
  --OutputDir=/hdfs/store/user/hjia38 \
  --HDFSProdDir None \
  --Experiment mucol \
  --DiskRequirements 50000

runWiscJobs.py \
  --WorkFlow KennyMG_vvqqh_30TeV \
  --Executable=runMG_Del.sh \
  --Arguments=mc-bkgvvqqh_30TeV.txt \
  --nJobs=1000 \
  --TransferInputFile=/nfs_scratch/hjia38/transferInputFiles.tar.gz,mc-bkgvvqqh_30TeV.txt\
  --OutputDir=/nfs_scratch/$USER \
  --HDFSProdDir None \
  --Experiment mucol \
  --DiskRequirements 50000

runWiscJobs.py \
  --WorkFlow KennyMG_2v4q_30TeV \
  --Executable=runMG_Del.sh \
  --Arguments=mc-bkg2v4q_30TeV.txt \
  --nJobs=1000 \
  --TransferInputFile=/nfs_scratch/hjia38/transferInputFiles.tar.gz,mc-bkg2v4q_30TeV.txt\
  --OutputDir=/nfs_scratch/$USER \
  --HDFSProdDir None \
  --Experiment mucol \
  --DiskRequirements 50000

